import Provider from "@/store/Provider";
import "./globals.css";
import { Inter } from "next/font/google";
import MyWrapper from "@/components/MyWrapper";
import StyledComponentsRegistry from "@/styles/StartStyle";
import "react-toastify/dist/ReactToastify.css";
import "../styles/preloader.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <Provider>
        <html lang="en">
          <body className={inter.className}>
            <StyledComponentsRegistry>
              <MyWrapper />
              {children}
            </StyledComponentsRegistry>
          </body>
        </html>
      </Provider>
    </>
  );
}
